"""Single-file prompt constants and registry for memory, answer, and judge templates."""

from __future__ import annotations


# Prompt used for extracting episodic memory from an exchange.
EPISODIC_EXTRACT_PROMPT = """TASK=EPISODIC_EXTRACTION
You are deciding whether the latest exchange contains episodic memory and creating a compact memory seed.
Return the exact DSL below.
Do not add any explanation before or after the DSL.
Return either NO_MEMORY or the exact DSL below.
If you return DSL, output only the DSL content.

SUMMARY_CONTENT: <one sentence>
CONTEXT: <context paragraph>
KEYWORDS: <comma-separated keywords>

Rules:
- Return NO_MEMORY only for pure greetings, acknowledgements, empty replies, or messages with no concrete facts, plans, events, preferences, relationships, items, or state changes worth storing.
- NO_MEMORY is only a low-value label for diagnostics; the system may still preserve the exchange as a low-salience memory seed, so prefer DSL whenever any concrete detail is present.
- Do not return NO_MEMORY when a concrete fact appears after an acknowledgement such as "Sure", "Thanks", "Great", or similar discourse text.
- Always create a memory seed for named places, area aliases, old area/hometown/neighborhood facts, disasters or incidents, infrastructure events, plans or goals, donations or volunteering, and location-bearing facts.
- Always create a memory seed for short factual items: book/movie/show titles, recommendations, equipment bought or refurbished, foods/snacks, pets or breeds, hobbies, practiced activities, methods/techniques, time-management tools, and image-described objects.
- If an exchange contains a list or partial list of concrete items, preserve the item set in SUMMARY_CONTENT, CONTEXT, and KEYWORDS instead of treating it as small talk.
- Preserve bridge facts that connect an area alias to a named place or event, such as "old area = a named county" or "that area was hit by a flood", in SUMMARY_CONTENT, CONTEXT, and KEYWORDS.
- SUMMARY_CONTENT must be one concise sentence about the exchange.
- CONTEXT must be one or two supporting background sentences for the same exchange.
- KEYWORDS must be short retrieval keywords or short phrases, not full sentences.
- Memory type is determined by the task and must not be emitted by the model.
- Do not output claims, claim statuses, claim ids, source_message_ids, links, timestamps, status flags, or operation sections.
- Claims are generated by a separate dedicated claim-text extraction stage.
"""

# Prompt used for deciding whether to continue or start a memory trajectory.
TRAJECTORY_MATCH_PROMPT = """TASK=TRAJECTORY_MATCH
Decide whether the new memory continues one of the candidate trajectories.
Return the exact DSL:

DECISION: <CONTINUE or NEW>
SELECTED_CANDIDATE: <T1/T2/T3 or none>
RATIONALE: <one short sentence>

Rules:
- CONTINUE only if the new memory clearly belongs to the same evolving trajectory as one candidate.
- Each candidate includes a trajectory summary for the whole thread and a latest update note for only the newest step.
- Use the trajectory summary as the primary signal; use the latest update note only as recent supporting context.
- Do not require the new memory to resemble only the latest update if the broader trajectory summary clearly matches.
- Same person, broad topic, or generic words such as community/support/art are not enough to CONTINUE.
- CONTINUE requires the same evolving event, project, item, place, count, or fact thread.
- Choose NEW when the memory is about a different item, place, event, count, or topic cluster under the same person unless it explicitly updates the existing thread.
- SELECTED_CANDIDATE must be one of the provided candidate labels when DECISION is CONTINUE.
- SELECTED_CANDIDATE must be none when DECISION is NEW.
- RATIONALE should briefly explain the shared evolving trajectory or why no candidate fits.
- Do not say candidates are merely related or similar.
"""

# Prompt used for adjudicating whether a new claim revises a previous claim.
CLAIM_TRANSITION_JUDGE_PROMPT = """TASK=CLAIM_TRANSITION_JUDGE
Decide whether the current claim clearly revises one of the candidate previous claims.
Return the exact DSL:

DECISION: <REVISE or ADD>
SELECTED_CANDIDATE: <P1/P2/P3 or none>
RATIONALE: <one short sentence>

Rules:
- Return REVISE only when the current claim is clearly an updated replacement for one candidate previous claim.
- Return ADD when the current claim is new, merely related, contradictory without replacement, or uncertain.
- SELECTED_CANDIDATE must be one of the provided candidate labels when DECISION is REVISE.
- SELECTED_CANDIDATE must be none when DECISION is ADD.
- RATIONALE should briefly explain what the new claim replaces or why it is only an addition.
- Do not say the claims are merely related or similar.
"""

# Prompt used for structured episodic extraction on remote closed-source models.
EPISODIC_EXTRACT_STRUCTURED_PROMPT = """TASK=EPISODIC_EXTRACTION_STRUCTURED
Decide whether the latest exchange contains episodic memory and create a compact memory seed.
Return structured data only through the provider's structured output channel.

Rules:
- Set has_memory=false only for pure greetings, acknowledgements, empty replies, or messages with no useful episodic memory.
- has_memory=false is only a low-value diagnostic label; the system may still preserve the exchange as a low-salience memory seed, so set has_memory=true whenever any concrete detail is present.
- Do not set has_memory=false when a concrete fact appears after an acknowledgement such as "Sure", "Thanks", "Great", or similar discourse text.
- Always create a memory seed for named places, area aliases, old area/hometown/neighborhood facts, disasters or incidents, infrastructure events, plans or goals, donations or volunteering, and location-bearing facts.
- Always create a memory seed for short factual items: book/movie/show titles, recommendations, equipment bought or refurbished, foods/snacks, pets or breeds, hobbies, practiced activities, methods/techniques, time-management tools, and image-described objects.
- If an exchange contains a list or partial list of concrete items, preserve the item set in summary_content, context, and keywords instead of treating it as small talk.
- Preserve bridge facts that connect an area alias to a named place or event, such as "old area = a named county" or "that area was hit by a flood", in summary_content, context, and keywords.
- Return only: summary_content, context, and keywords.
- Do not include claims, claim statuses, source_message_ids, memory_type, timestamp, links, status_flags, claim ids, or ops; those are generated by later stages.
- summary_content must be a single event sentence for this exchange.
- context must be one or two supporting background sentences for the same event.
- keywords must be short keywords or short phrases, not full sentences.
- Claims are generated by a separate dedicated claim-text extraction stage.
"""

EPISODIC_CLAIM_TEXT_EXTRACT_PROMPT = """TASK=EPISODIC_CLAIM_TEXT_EXTRACT
Rewrite the current exchange into readable, source-grounded atomic claim sentences.

Return exactly:
HAS_CLAIMS: true|false
REASON: <short reason or none>

[CLAIMS]
- status=<active/deprecated/contradictory/needs-confirmation> | source_message_ids=<comma-separated raw ids> | supporting_quote=<verbatim raw quote> | text=<one complete readable factual sentence>

Rules:
1. Use only facts explicitly stated in the raw messages.
2. Resolve speaker names from the raw source lines. If the raw line says "(Melanie): my son", write "Melanie's son", not "Caroline's son", "the user", or "the assistant".
3. Do not output transcript fragments, acknowledgements, greetings, discourse markers, or sentence openers.
4. For list-like utterances, output one item-level claim for every stated item; you may also add one inventory claim, but item-level claims are required.
5. Keep exact names, titles, places, counts, instruments, event labels, and item names using the raw surface phrase.
6. Do not collapse books, instruments, cities, places, activities, events, painted objects, or counts into broad theme claims.
7. When the raw message enumerates specific items, preserve each exact item as its own claim text.
8. Do not replace a concrete raw noun phrase with a broader category: if the raw text says "sunset", keep "sunset", not only "nature-inspired artwork".
9. You may add broader context, but the original source phrase must remain visible in at least one claim.
10. supporting_quote must be copied from the raw source message and must support the claim.
11. source_message_ids must use raw ids from the current exchange only.
"""

EPISODIC_CLAIM_TEXT_EXTRACT_STRUCTURED_PROMPT = """TASK=EPISODIC_CLAIM_TEXT_EXTRACT_STRUCTURED
Rewrite the current exchange into readable, source-grounded atomic claim sentences.
Return structured data only through the provider's structured output channel.

Rules:
- Use only facts explicitly stated in the raw messages.
- Resolve speaker names from the raw source lines. If the raw line says "(Melanie): my son", write "Melanie's son", not "Caroline's son", "the user", or "the assistant".
- claim text must be a complete readable factual sentence, not a transcript fragment or broad summary.
- For list-like utterances, include item-level claims for every stated item.
- Preserve exact raw surface phrases for names, titles, places, counts, instruments, events, and items.
- Do not collapse books, instruments, cities, places, activities, events, painted objects, or counts into umbrella-only claims.
- Do not replace concrete raw noun phrases with broader categories: if raw says "sunset", keep "sunset", not only "nature-inspired artwork".
- You may include broader context, but the original source phrase must remain visible in at least one claim.
- supporting_quote must be copied from the raw source message and must support the claim.
"""

CLAIM_SIGNAL_EXTRACT_PROMPT = """TASK=CLAIM_SIGNAL_EXTRACT
Extract validated retrieval and display signals from the supplied readable claims and source snippets.

Return exactly these sections:
[EXACT_TERMS]
- surface=<raw substring> | category=<title/place/item/instrument/symbol/count/research_topic/event_type/other> | source_claim_id=<claim id> | source_message_ids=<comma-separated raw ids>

[FACETS]
- relation=<relationship_status/gender_identity/home_country/activity_location/research_topic/art_style/event_type/other> | value=<raw substring> | entity=<raw substring or none> | value_span=<raw substring or none> | source_claim_id=<claim id> | source_message_ids=<comma-separated raw ids>

[DISPLAY_ITEMS]
- <readable item/title/place/count/name from the source>

[DISPLAY_NAMED_ENTITIES]
- <readable named entity from the source>

[DISPLAY_COUNTS]
- <readable count/value from the source>

[DISPLAY_KEY_FACTS]
- <complete readable fact sentence grounded in the supplied claims>

Rules:
1. Every exact term, facet value, value_span, display item, named entity, and count must be copied from a supplied claim or source snippet.
2. Do not invent normalized names or semantic replacements.
3. Do not output fragments such as "Here to a", "Love and", "Now the", "Excited for", "Respect for", or acknowledgements such as "Wow".
4. Prefer concise useful retrieval/display signals over exhaustive noisy spans.
5. If a section has no valid values, write "- none".
"""

CLAIM_SIGNAL_EXTRACT_STRUCTURED_PROMPT = """TASK=CLAIM_SIGNAL_EXTRACT_STRUCTURED
Extract validated retrieval and display signals from readable claims and source snippets.
Return structured data only through the provider's structured output channel.

Rules:
- Every surface/value/value_span/display value must be copied from a supplied claim or source snippet.
- Do not invent normalized names or semantic replacements.
- Do not output transcript fragments, greetings, acknowledgements, or sentence opener fragments.
- Prefer concise useful retrieval/display signals over exhaustive noisy spans.
"""

# Prompt used for targeted repair when source-grounded preservation audit finds missing exact claims.
EPISODIC_CLAIM_PRESERVATION_REPAIR_PROMPT = """TASK=EPISODIC_CLAIM_PRESERVATION_REPAIR
The previous episodic memory parsed successfully, but deterministic source-grounded audit found high-confidence exact details missing from claims.
Return a complete repaired episodic DSL only.
Do not add commentary before or after the DSL.
Place the repaired DSL content inside:
BEGIN_MEMORY_DSL
...
END_MEMORY_DSL

Rules:
- Preserve all valid existing claims unless they are contradicted by the raw exchange.
- Add or revise claims so every missing candidate appears with the exact surface phrase in a claim text when the raw source supports it.
- Use only raw message ids from the current exchange as source_message_ids.
- Keep source_message_ids as the smallest sufficient supporting set.
- For list-like candidates, include item-level claims for each missing item.
- Do not invent facts, infer unsupported relations, or rewrite exact candidates into broader paraphrases.
- Keep SUMMARY_CONTENT, CONTEXT, KEYWORDS, and [CLAIMS].
"""

# Prompt used for structured trajectory matching on remote closed-source models.
TRAJECTORY_MATCH_STRUCTURED_PROMPT = """TASK=TRAJECTORY_MATCH_STRUCTURED
Decide whether the new memory continues one of the shortlisted candidate trajectories.
Return structured data only through the provider's structured output channel.

Rules:
- Choose CONTINUE only if the new memory clearly belongs to the same evolving trajectory as one candidate.
- Each candidate includes a trajectory summary for the whole thread and a latest update note for only the newest step.
- Use the trajectory summary as the primary signal; use the latest update note only as recent supporting context.
- Do not require the new memory to resemble only the latest update if the broader trajectory summary clearly matches.
- Same person, broad topic, or generic words such as community/support/art are not enough to CONTINUE.
- CONTINUE requires the same evolving event, project, item, place, count, or fact thread.
- Choose NEW when the memory is about a different item, place, event, count, or topic cluster under the same person unless it explicitly updates the existing thread.
- selected_candidate must be null when decision is NEW.
- selected_candidate must be one of the provided candidate labels when decision is CONTINUE.
- rationale should briefly explain the shared evolving trajectory or why no candidate fits.
- Do not say candidates are merely related or similar.
"""

# Prompt used for structured claim-transition adjudication on remote closed-source models.
CLAIM_TRANSITION_JUDGE_STRUCTURED_PROMPT = """TASK=CLAIM_TRANSITION_JUDGE_STRUCTURED
Decide whether the current claim clearly revises one of the shortlisted previous candidate claims.
Return structured data only through the provider's structured output channel.

Rules:
- Return REVISE only when the current claim is clearly an updated replacement for one candidate previous claim.
- Return ADD when the current claim is new, merely related, contradictory without replacement, or uncertain.
- selected_candidate must be null when decision is ADD.
- selected_candidate must be one of the provided candidate labels when decision is REVISE.
- rationale should briefly explain what the new claim replaces or why it is only an addition.
- Do not say the claims are merely related or similar.
"""

# Prompt used for repairing malformed structured outputs.
STRUCTURE_REPAIR_PROMPT = """TASK=STRUCTURE_REPAIR
The previous output failed parsing or validation.
Rewrite it into the exact DSL again and fix only the listed issues.
Do not add commentary before or after the requested repaired content.
Place the repaired DSL content inside:
BEGIN_MEMORY_DSL
...
END_MEMORY_DSL
"""

# Prompt used for final answer generation from retrieved context.
ANSWER_GENERATION_PROMPT = """TASK=ANSWER_GENERATION
Answer the final user query using the provided episodic memories, supporting source messages, and current question.

Rules:
1. Use only supplied memory and source evidence; do not guess.
2. Prefer a direct answer with exact names, dates, places, counts, and items when present.
3. Use source messages to confirm exact wording or resolve contradictions.
4. If relevant evidence is contradictory or insufficient, say so briefly instead of asserting a false fact.
"""

# Prompt used for LOCOMO answer generation from retrieved context.
LOCOMO_ANSWER_GENERATION_PROMPT = """TASK=LOCOMO_ANSWER_GENERATION
Answer ONE LOCOMO question using only the retrieved memories and source messages.

Rules:
1. Ground every fact in the retrieved context; if evidence is insufficient, abstain briefly.
2. Preserve exact source terms for names, titles, places, dates, counts, activities, and items.
3. For list, comparison, or multi-entity questions, include all in-scope supported items and cover each entity explicitly.
4. For count questions, answer with an exact count only when completed distinct events are supported; otherwise state a retrieved-evidence lower bound.
5. Do not add unsupported extras, future plans as completed events, duplicate event mentions, broad paraphrases, or conversational filler.
6. If an evidence synthesis block is supplied, trust its counted/excluded event decisions.

Return only the final answer text.
"""

# Prompt used to synthesize grounded LOCOMO evidence before final answer output.
LOCOMO_ANSWER_EVIDENCE_SYNTHESIS_PROMPT = """TASK=LOCOMO_ANSWER_EVIDENCE_SYNTHESIS
Legacy structured LOCOMO evidence synthesis.

Input contains a LOCOMO question followed by retrieved memory/wiki/source evidence.

Rules:
1. Use only retrieved evidence. If it cannot answer the question, set can_answer=false, leave final_answer empty, and explain the gap in abstain_reason.
2. Preserve exact source terms for names, titles, places, dates, counts, activities, and items.
3. supporting_source_refs must use only visible refs such as D8:4, and each ref must support the requested answer family.
4. Count distinct completed events only. Exclude future plans, intentions, reactions, duplicate mentions, general hobbies, and uncertain candidates.
5. Count final_answer must be natural language, not a bare number; use an exact count only when complete evidence supports it, otherwise state a retrieved-evidence lower bound.
6. Date/time answers must use source line date=... fields, snapshot Timestamp lines, and the ## Temporal Anchors block; resolve terms such as "yesterday", "one year ago", "last month", or "last Friday" to the grounded Temporal Anchor target when available.
7. For lists/events/preferences, include every in-scope source-backed specific item and avoid scope-mismatched extras.
8. For bridge/alias facts, answer with the concrete source-backed value, e.g. "West County" rather than "old area".

Return structured data only. If structured output is unavailable, return only a JSON object matching the same fields.
"""

LOCOMO_ANSWER_FREEFORM_PROMPT = """TASK=LOCOMO_ANSWER_FREEFORM
Answer one LOCOMO question using only the retrieved context.

Output plain text in this exact lightweight format:
Answer: <final answer>
Rationale: <one brief source-grounded reason>

Rules:
1. Grounding: use only retrieved evidence; if unsupported, write exactly "Answer: The retrieved context does not support an answer to this question."
2. Form: answer the requested type directly. Dates need a date/time value, counts need a supported natural-language count, and places/people need the concrete entity.
3. Specificity: preserve exact source terms for names, titles, places, dates, counts, activities, and items; prefer specific items over broad categories.
4. Temporal Anchors: if a source uses relative time such as "last week", "last Friday", "last month", "last year", or "one year ago", answer with the resolved Temporal Anchor target; do not collapse it to the source message date.
5. Coverage: for list/event/preference questions, include all in-scope supported items and omit unsupported or scope-mismatched extras.
6. Keep the answer concise; put only the source-grounded reason in Rationale.
"""

LOCOMO_ANSWER_TYPE_VERIFICATION_PROMPT = """TASK=LOCOMO_ANSWER_TYPE_VERIFICATION
Verify whether a free-form LOCOMO answer has the answer type required by the question.

Input contains:
- question
- expected_answer_type from deterministic question analysis
- observed_answer_type from deterministic answer-text analysis
- answer
- short diagnostics

Rules:
1. Judge only answer form, not factual correctness.
2. Match the requested type: date/time, count, list, place, person, boolean, or value.
3. Reject wrong-form answers such as a count for a date question or a time expression for a place question.
4. If mismatched, provide one concise repair instruction using only retrieved evidence.

Return structured data only. If structured output is unavailable, return only a JSON object matching the same fields.
"""

LOCOMO_ANSWER_REPAIR_ARBITRATION_PROMPT = """TASK=LOCOMO_ANSWER_REPAIR_ARBITRATION
Compare an initial LOCOMO answer with a repaired answer. Choose which answer should be used.

Input contains the question, expected answer type, repair issue, both candidate answers, and compact retrieved-evidence signals.

Rules:
1. Do not write a new answer. Choose only keep_initial, use_repair, or safe_abstain.
2. Use only supplied evidence signals; do not use gold answers, judge labels, metrics, or outside knowledge.
3. For date/time questions, prefer the explicit resolved Temporal Anchor target. If the target is a span, month-year, year, or fuzzy relative phrase, preserve that target and do not collapse it to the anchor/source date.
4. Reject a repaired answer if it drops a source-backed date, count, place, person, boolean value, bridge target, or required list item from the initial answer.
5. Use the repaired answer only when it better matches the question type/scope and remains source-supported.
6. Choose safe_abstain only when neither candidate is supported by the supplied evidence.

Return structured data only. If structured output is unavailable, return only a JSON object matching the same fields.
"""

# Prompt used to arbitrate high-risk LOCOMO count candidates.
LOCOMO_ANSWER_COUNT_VALIDATION_PROMPT = """TASK=LOCOMO_ANSWER_COUNT_VALIDATION
Validate candidate count events using only the supplied source lines.

Input contains one count question and candidate events with event_id, source refs, source lines, and deterministic reasons.

Rules:
1. Use only supplied source lines. Do not use the gold answer, outside knowledge, missing context, new events, or new refs.
2. Decide only supplied event_id values: COUNT, EXCLUDE, or UNCERTAIN.
3. COUNT only events supported under the question's scope. Planned/intended events count only when the question asks for planned scope; completed-event questions exclude future plans.
4. EXCLUDE duplicates, unrelated events, pure reactions, passive observations, and candidates whose source lines do not support the question.
5. Use UNCERTAIN for plausible but insufficient evidence.
6. Image captions, pronouns, adjacent wording, and source-derived candidates such as pronoun plus image caption may support an event when the source lines clearly connect them.
7. final_count must equal COUNT decisions, except states/possessions/mentions with an explicit numeric source count.

Return structured data only. If structured output is unavailable, return only a JSON object matching the same fields.
"""

# Prompt used for repairing LOCOMO final answers after deterministic post-checks.
LOCOMO_ANSWER_REPAIR_PROMPT = """TASK=LOCOMO_ANSWER_REPAIR
Repair one LOCOMO final answer using only the supplied question, previous answer, and supported surface values.

Rules:
1. Return plain natural-language answer text only. Do not return JSON, Markdown code, field names, or a structured object.
2. Preserve valid supported content. If MUST_KEEP_SUPPORTED_ITEMS is not "none", every listed item must remain.
3. Apply the repair instruction: remove unsupported extras, wrong counts, wrong answer type, or scope-mismatched items.
4. If SUPPORTED_LIST_ITEMS contains in-scope answers, include them without adding unsupported items.
5. If a source-backed bridge value is supplied, use the concrete value instead of the alias.
6. For date/time repairs, use TEMPORAL_CANDIDATES resolved_answer_text as the answer target when present; do not replace relative targets with source dates.
7. If supported values do not answer the question, return a brief natural-language abstention.
"""

# Prompt used for episodic trajectory retrieval summary generation.
TRAJECTORY_RETRIEVAL_SUMMARY_PROMPT = """TASK=TRAJECTORY_RETRIEVAL_SUMMARY
Create a markdown retrieval summary for ONE episodic trajectory using only the supplied grounded internal memory state.

Goal:
- produce a retrieval-oriented synopsis for coarse trajectory selection
- preserve exact names, items, and specific facts
- keep older but query-relevant facts visible even when later snapshots shift topic
- surface uncertainty or conflicts explicitly instead of hiding them

Required headings:
## Profile / Stable Facts
## Item Sets / Named Entities
## Relations / Temporal Updates
## Conflicts / Uncertainty

Rules:
1. Use only the supplied claims, facets, exact terms, and recent snapshot notes.
2. Preserve exact titles, books, recipes, instruments, symbols, places, and named items.
3. Keep list items explicit; do not collapse them into broad themes.
4. Do not let the newest update erase older item sets, places, events, dates, or counts from the trajectory.
5. Do not replace concrete source phrases with broad categories: keep "sunset" visible even if you also mention "artwork".
6. Mention contradictory or uncertain facts under Conflicts / Uncertainty instead of resolving them yourself.
7. Do not add commentary, preamble, or conclusions outside the markdown sections.
8. Exclude filler words, acknowledgements, discourse markers, and casual fragments from the useful retrieval content.
"""

# Prompt used for wiki page planning.
WIKI_PAGE_PLAN_PROMPT = """TASK=WIKI_PAGE_PLAN
Plan a compact sample-level wiki graph from the provided candidate seed manifest.

Return markdown only with the exact heading:
## Pages

Then emit one bullet per page:
- page_type=<index/entity/topic/inventory> | title=<title> | slug=<slug> | trajectories=<comma-separated trajectory ids> | entities=<comma-separated entities> | links=<comma-separated page slugs>

Rules:
1. Always include exactly one index page.
2. Treat each input block as a candidate seed that already groups related trajectories; refine or select from those seeds instead of inventing broad new groupings.
3. Create entity pages when a person/entity appears across multiple trajectories.
4. Create inventory pages for list/count/item-heavy facts such as activities, books, recipes, instruments, symbols, places, wins, dogs, or repeated events.
5. Create topic pages only when they add navigation value beyond entity or inventory pages.
6. Keep pages compact and specific; avoid broad pages that overlap heavily with existing entity or inventory coverage.
7. Prefer explicit evidence coverage over narrative grouping.
8. Use trajectory historical evidence cards as first-class evidence; do not rely only on a trajectory's latest summary.
9. If a card exposes a specific item, place, event, count, or source anchor, cover it in a non-index page whenever possible.
"""

# Prompt used for wiki page compilation.
WIKI_PAGE_COMPILE_PROMPT = """TASK=WIKI_PAGE_COMPILE
Compile one wiki page from the supplied page metadata, representative trajectory summaries, and historical trajectory evidence cards.

Return markdown only with these headings:
## Overview
## Key Facts
## Items / Counts
## Linked Trajectories
## Conflicts / Uncertainty

Rules:
1. Use only supplied linked trajectory ids, dominant entities, exact terms, facet values, representative trajectory summaries, and historical evidence cards.
2. Keep exact names, items, places, counts, and titles.
3. For inventory pages, favor explicit item lists over prose.
4. Preserve enumerated items and counts explicitly; do not collapse them into broad narrative summaries.
5. Do not replace a concrete source phrase with a broader category: if an evidence card contains "sunset", keep "sunset", not only "nature-inspired artwork".
6. Do not add speculative links or inferred facts not stated in the supplied inputs.
7. In Items / Counts, use only readable display items, readable counts, and readable key facts.
8. If a latest summary and historical card emphasize different facts, present the historical facts in their own concrete bullets instead of dropping them.
9. Do not dump Dominant exact terms verbatim; ignore any low-confidence or fragment-like signal.
10. Do not write placeholder descriptions such as "Not provided", "Unknown", "N/A", "None provided", "No specific key facts", or "No explicit items".
11. Describe a linked trajectory only when its representative summary or evidence card is supplied; otherwise leave the trajectory id without a fabricated description.
12. The system may rewrite the final Linked Trajectories section deterministically, so keep that section concise.
"""

# Prompt used for coverage-aware reranking over wiki pages.
WIKI_PAGE_RERANK_PROMPT = """TASK=WIKI_PAGE_RERANK
You are selecting the best set of wiki pages for answering ONE question.

Return exactly:
SELECTED: <comma-separated candidate labels in best-to-worst order>
RATIONALES:
- <label>: <one short reason>

Rules:
1. Select pages that jointly maximize answer coverage.
2. Prefer complementary entity/topic/inventory coverage over redundant theme overlap.
3. Favor pages with explicit evidence relevant to the question, not pages that are merely topically similar.
4. Do not invent new candidates or reorder labels not present in the candidate list.
"""

# Prompt used for coverage-aware reranking over trajectory summaries.
TRAJECTORY_SET_RERANK_PROMPT = """TASK=TRAJECTORY_SET_RERANK
You are selecting the best set of episodic trajectory summaries for answering ONE question.

Return exactly:
SELECTED: <comma-separated candidate labels in best-to-worst order>
RATIONALES:
- <label>: <one short reason>

Rules:
1. Select candidates that jointly maximize answer coverage, not just single-summary relevance.
2. Prefer complementary evidence over redundant summaries.
3. Favor exact facts, named items, and trajectories that together can answer multi-hop questions completely.
4. For list, count, comparison, or multi-entity questions, prefer candidates that add different item/place/event/entity subfacts.
5. Penalize trajectories that repeat the same entity or topic without adding new evidence.
6. Use only explicit evidence from the supplied summaries; do not justify selections with vague thematic similarity.
7. Do not invent new candidates or reorder labels not present in the candidate list.
8. The SELECTED line must contain only the chosen labels, ordered from strongest to weakest.
"""

# Prompt used for MedMT answer generation from retrieved context.
MEDMT_ANSWER_GENERATION_PROMPT = """TASK=MEDMT_ANSWER_GENERATION
You are answering ONE MedMT-Bench question.

You will be given:
- CATEGORY: the main evaluation category
- SUBTYPE: the fine-grained subtype
- SCENE_TAG: the scenario label
- SUBSET_KEY: the benchmark subset file key
- RUBRIC: the test point that defines the required behavior
- RETRIEVED_CONTEXT: the episodic memories, wiki-routed evidence, source messages, and conflict block returned by retrieval
- FINAL_USER_TURN: the current question to answer

Rules:
1. Use only the retrieved context and the final user turn. Do not assume facts not grounded in the retrieved material.
2. Treat Retrieved Episodic Memory as the main evidence for reconstructing history and constraints.
3. Use Supporting Source Messages only to confirm exact details, conflicting wording, names, medications, places, or other critical specifics.
4. First identify the key historical facts or constraints that matter for this query.
5. Then identify the key action required by the rubric and category.
6. Your final answer must explicitly perform that key action. Do not give merely generic or medically plausible advice if the required action is different.
7. If the retrieved context contains unresolved contradiction or uncertainty relevant to the query, explicitly name it and ask the user to confirm before proceeding substantively.

Category-specific guidance:
- Long-Context Memory and Understanding:
  Resolve the correct earlier person, disease, symptom, time, medication, or detail before answering. Do not give generic advice that could fit multiple referents.
- Resistance to Contextual Interference:
  Follow the governing instruction or constraint in the retrieved context and current turn. Ignore distracting, conflicting, or stale context that should not control the answer.
- Instruction Clarification / Information Contradiction:
  If the latest turn conflicts with relevant earlier history, explicitly point out the contradiction and ask the user to confirm or clarify before continuing.

Return only the final answer text. Do not output hidden reasoning, bullets about your internal procedure, or extra labels.
"""

_LOCOMO_JUDGE_INSTRUCTION_BODY = """Evaluate the candidate answer against the question and gold answer.

Equivalence Policy:
- Allow semantic equivalence, near-synonyms, ordering/format variants, harmless modifiers, and concise or longer phrasing with the same meaning.
- Accept date variants for the same time point, e.g. "May 7th" and "7 May"; an unanchored relative date such as "last Tuesday" is PARTIAL, and a clearly wrong date is INCORRECT.
- Treat source-backed aliases as covered: "LGBTQ support group" covers "support group"; "LGBTQ pride parade" covers "pride parade"; "shared her journey at a school event and encouraged students" covers "school speech"; "mentorship program for LGBTQ youth" covers "mentoring program".
- Harmless same-category extras are allowed unless they change the requested scope, contradict the gold answer, or replace a required item.

Strict Cases:
- Counts are strict: "Twice", "2 times", and "two confirmed rejections" are equivalent, but an unqualified wrong count is INCORRECT.
- A retrieved-evidence lower bound such as "The retrieved evidence confirms one rejection" is PARTIAL when the gold requires more.
- Missing a required list item is PARTIAL; for example, omits "school speech" from "pride parade, school speech, support group".
- Wrong entity, polarity, count, time, or place is INCORRECT.

Verdicts:
- CORRECT: all required gold facts/items are covered and no contradiction changes the answer.
- PARTIAL: at least one required fact is covered, but required content is missing or qualified as a lower bound.
- INCORRECT: no required fact matches, or the answer reverses/changes the core meaning."""

_LOCOMO_JUDGE_TEXT_OUTPUT_RULES = """Respond with ONLY ONE WORD:
- CORRECT
- PARTIAL
- INCORRECT"""

_LOCOMO_JUDGE_STRUCTURED_OUTPUT_RULES = """Return structured data only through the provider's structured output channel.

Rules:
- verdict must be CORRECT, PARTIAL, or INCORRECT."""

# Prompt used for LOCOMO answer judging.
LOCOMO_JUDGE_PROMPT = (
    "TASK=LOCOMO_JUDGE\n"
    + _LOCOMO_JUDGE_INSTRUCTION_BODY
    + "\n\n"
    + _LOCOMO_JUDGE_TEXT_OUTPUT_RULES
)

# Prompt used for structured LOCOMO judging on remote closed-source models.
LOCOMO_JUDGE_STRUCTURED_PROMPT = (
    "TASK=LOCOMO_JUDGE_STRUCTURED\n"
    + _LOCOMO_JUDGE_INSTRUCTION_BODY
    + "\n\n"
    + _LOCOMO_JUDGE_STRUCTURED_OUTPUT_RULES
)

_MEDMT_JUDGE_INSTRUCTION_BODY = """Evaluate ONE MedMT-Bench candidate answer using only the supplied dialogue and rubric.

Inputs include CATEGORY, SUBTYPE, FULL_DIALOGUE, FINAL_USER_TURN, RUBRIC, and CANDIDATE_ANSWER.

General Policy:
1. Judge substance, not exact wording. Allow semantic equivalence, formatting differences, and minor harmless errors.
2. Do not use outside assumptions. Generally helpful medical advice is not enough unless it satisfies the rubric.
3. Identify the relevant historical fact/constraint, the final user request, and whether the candidate performs the required behavior.
4. Mark generic, ambiguous, or key-step-missing answers INCORRECT.

Category Rules:
- Long-Context Memory and Understanding: the answer must resolve the correct earlier person, condition, symptom, medication, time, or detail. Confusing referents is INCORRECT.
- Resistance to Contextual Interference: the answer must follow the governing system/task constraint despite distracting or stale context. Obeying conflicting prior turns is INCORRECT.
- Instruction Clarification / Information Contradiction: the answer must explicitly identify the contradiction and request confirmation or clarification before proceeding substantively."""

_MEDMT_JUDGE_TEXT_OUTPUT_RULES = """Respond with ONLY ONE WORD:
- CORRECT if the candidate answer fully satisfies the rubric in substance.
- PARTIAL if the candidate answer satisfies at least one substantive rubric requirement but misses key steps, constraints, or historical facts.
- INCORRECT if the candidate answer satisfies no substantive rubric requirement or violates the core instruction/history constraint."""

_MEDMT_JUDGE_STRUCTURED_OUTPUT_RULES = """Return structured data only through the provider's structured output channel.

Rules:
- verdict must be CORRECT, PARTIAL, or INCORRECT."""

# Prompt used for MedMT rubric judging.
MEDMT_JUDGE_PROMPT = (
    "TASK=MEDMT_JUDGE\n"
    + _MEDMT_JUDGE_INSTRUCTION_BODY
    + "\n\n"
    + _MEDMT_JUDGE_TEXT_OUTPUT_RULES
)

# Prompt used for structured MedMT judging on remote closed-source models.
MEDMT_JUDGE_STRUCTURED_PROMPT = (
    "TASK=MEDMT_JUDGE_STRUCTURED\n"
    + _MEDMT_JUDGE_INSTRUCTION_BODY
    + "\n\n"
    + _MEDMT_JUDGE_STRUCTURED_OUTPUT_RULES
)


SEMANTIC_METRIC_SCHEMA_PROMPT = """TASK=SEMANTIC_METRIC_SCHEMA
Build a compact scoring schema for semantic answer comparison.

Inputs:
- QUESTION: the benchmark question.
- REFERENCE_ANSWER: the gold answer.

Rules:
- Create only slots that are required to compare the reference answer.
- Use stable lowercase snake_case slot_id values.
- For list answers, create one slot for the item family, not one slot per item.
- For count/date/place/person/entity answers, create one targeted slot.
- Do not include slots that are not implied by the reference answer.
- Return structured data only through the provider's structured output channel."""


SEMANTIC_METRIC_EXTRACT_PROMPT = """TASK=SEMANTIC_METRIC_EXTRACT
Extract canonical answer values according to a provided scoring schema.

Inputs:
- SCHEMA_JSON: slots to fill.
- ANSWER_TEXT: the answer to inspect.

Rules:
- Extract values only from ANSWER_TEXT.
- Do not use outside knowledge or infer unstated facts.
- Canonicalize obvious paraphrases and formatting differences.
- For list slots, put each item as a separate canonical value.
- If a slot is not supported by ANSWER_TEXT, return an empty canonical_values list.
- Return structured data only through the provider's structured output channel."""


RETRIEVAL_REFLECTION_PROMPT = """TASK=RETRIEVAL_REFLECTION
Analyze a weak LOCOMO retrieval and produce evidence-seeking hints for a second retrieval attempt.

Inputs:
- QUESTION: the original benchmark question.
- INITIAL_ANSWER: the first answer, usually an abstention or unsupported answer.
- INITIAL_RETRIEVAL_SUMMARY: compact diagnostics from the first retrieval.
- WIKI_DIRECTORY: available wiki pages for the same conversation only.

Rules:
- Do not answer the question.
- Infer what evidence must be found, not what the final answer should be.
- Prefer raw surface terms that may appear in memory or raw conversation turns.
- Use candidate_page_slugs only when a listed wiki slug plausibly matches the evidence need.
- Keep rewritten_query concise and search-oriented.
- Return structured data only through the provider's structured output channel."""


PROMPT_REGISTRY: dict[str, str] = {
    "episodic_extract": EPISODIC_EXTRACT_PROMPT,
    "episodic_claim_text_extract": EPISODIC_CLAIM_TEXT_EXTRACT_PROMPT,
    "episodic_claim_text_extract_structured": EPISODIC_CLAIM_TEXT_EXTRACT_STRUCTURED_PROMPT,
    "claim_signal_extract": CLAIM_SIGNAL_EXTRACT_PROMPT,
    "claim_signal_extract_structured": CLAIM_SIGNAL_EXTRACT_STRUCTURED_PROMPT,
    "trajectory_match": TRAJECTORY_MATCH_PROMPT,
    "claim_transition_judge": CLAIM_TRANSITION_JUDGE_PROMPT,
    "episodic_extract_structured": EPISODIC_EXTRACT_STRUCTURED_PROMPT,
    "trajectory_match_structured": TRAJECTORY_MATCH_STRUCTURED_PROMPT,
    "claim_transition_judge_structured": CLAIM_TRANSITION_JUDGE_STRUCTURED_PROMPT,
    "repair": STRUCTURE_REPAIR_PROMPT,
    "episodic_claim_preservation_repair": EPISODIC_CLAIM_PRESERVATION_REPAIR_PROMPT,
    "answer_generation": ANSWER_GENERATION_PROMPT,
    "locomo_answer_generation": LOCOMO_ANSWER_GENERATION_PROMPT,
    "locomo_answer_evidence_synthesis": LOCOMO_ANSWER_EVIDENCE_SYNTHESIS_PROMPT,
    "locomo_answer_freeform": LOCOMO_ANSWER_FREEFORM_PROMPT,
    "locomo_answer_type_verification": LOCOMO_ANSWER_TYPE_VERIFICATION_PROMPT,
    "locomo_answer_repair_arbitration": LOCOMO_ANSWER_REPAIR_ARBITRATION_PROMPT,
    "locomo_answer_count_validation": LOCOMO_ANSWER_COUNT_VALIDATION_PROMPT,
    "locomo_answer_repair": LOCOMO_ANSWER_REPAIR_PROMPT,
    "medmt_answer_generation": MEDMT_ANSWER_GENERATION_PROMPT,
    "trajectory_retrieval_summary": TRAJECTORY_RETRIEVAL_SUMMARY_PROMPT,
    "wiki_page_plan": WIKI_PAGE_PLAN_PROMPT,
    "wiki_page_compile": WIKI_PAGE_COMPILE_PROMPT,
    "wiki_page_rerank": WIKI_PAGE_RERANK_PROMPT,
    "trajectory_set_rerank": TRAJECTORY_SET_RERANK_PROMPT,
    "locomo_judge": LOCOMO_JUDGE_PROMPT,
    "medmt_judge": MEDMT_JUDGE_PROMPT,
    "locomo_judge_structured": LOCOMO_JUDGE_STRUCTURED_PROMPT,
    "medmt_judge_structured": MEDMT_JUDGE_STRUCTURED_PROMPT,
    "semantic_metric_schema": SEMANTIC_METRIC_SCHEMA_PROMPT,
    "semantic_metric_extract": SEMANTIC_METRIC_EXTRACT_PROMPT,
    "retrieval_reflection": RETRIEVAL_REFLECTION_PROMPT,
}

PROMPT_NAME_TO_VARIABLE: dict[str, str] = {
    "episodic_extract": "EPISODIC_EXTRACT_PROMPT",
    "episodic_claim_text_extract": "EPISODIC_CLAIM_TEXT_EXTRACT_PROMPT",
    "episodic_claim_text_extract_structured": "EPISODIC_CLAIM_TEXT_EXTRACT_STRUCTURED_PROMPT",
    "claim_signal_extract": "CLAIM_SIGNAL_EXTRACT_PROMPT",
    "claim_signal_extract_structured": "CLAIM_SIGNAL_EXTRACT_STRUCTURED_PROMPT",
    "trajectory_match": "TRAJECTORY_MATCH_PROMPT",
    "claim_transition_judge": "CLAIM_TRANSITION_JUDGE_PROMPT",
    "episodic_extract_structured": "EPISODIC_EXTRACT_STRUCTURED_PROMPT",
    "trajectory_match_structured": "TRAJECTORY_MATCH_STRUCTURED_PROMPT",
    "claim_transition_judge_structured": "CLAIM_TRANSITION_JUDGE_STRUCTURED_PROMPT",
    "repair": "STRUCTURE_REPAIR_PROMPT",
    "episodic_claim_preservation_repair": "EPISODIC_CLAIM_PRESERVATION_REPAIR_PROMPT",
    "answer_generation": "ANSWER_GENERATION_PROMPT",
    "locomo_answer_generation": "LOCOMO_ANSWER_GENERATION_PROMPT",
    "locomo_answer_evidence_synthesis": "LOCOMO_ANSWER_EVIDENCE_SYNTHESIS_PROMPT",
    "locomo_answer_freeform": "LOCOMO_ANSWER_FREEFORM_PROMPT",
    "locomo_answer_type_verification": "LOCOMO_ANSWER_TYPE_VERIFICATION_PROMPT",
    "locomo_answer_repair_arbitration": "LOCOMO_ANSWER_REPAIR_ARBITRATION_PROMPT",
    "locomo_answer_count_validation": "LOCOMO_ANSWER_COUNT_VALIDATION_PROMPT",
    "locomo_answer_repair": "LOCOMO_ANSWER_REPAIR_PROMPT",
    "medmt_answer_generation": "MEDMT_ANSWER_GENERATION_PROMPT",
    "trajectory_retrieval_summary": "TRAJECTORY_RETRIEVAL_SUMMARY_PROMPT",
    "wiki_page_plan": "WIKI_PAGE_PLAN_PROMPT",
    "wiki_page_compile": "WIKI_PAGE_COMPILE_PROMPT",
    "wiki_page_rerank": "WIKI_PAGE_RERANK_PROMPT",
    "trajectory_set_rerank": "TRAJECTORY_SET_RERANK_PROMPT",
    "locomo_judge": "LOCOMO_JUDGE_PROMPT",
    "medmt_judge": "MEDMT_JUDGE_PROMPT",
    "locomo_judge_structured": "LOCOMO_JUDGE_STRUCTURED_PROMPT",
    "medmt_judge_structured": "MEDMT_JUDGE_STRUCTURED_PROMPT",
    "semantic_metric_schema": "SEMANTIC_METRIC_SCHEMA_PROMPT",
    "semantic_metric_extract": "SEMANTIC_METRIC_EXTRACT_PROMPT",
    "retrieval_reflection": "RETRIEVAL_REFLECTION_PROMPT",
}


def load_prompt(name: str) -> str:
    if name not in PROMPT_REGISTRY:
        raise KeyError(f"Unknown prompt template: {name}")
    return PROMPT_REGISTRY[name]


def list_prompts() -> list[str]:
    return sorted(PROMPT_REGISTRY)
